package uk.co.praguematica.urlmapping;

public enum MappingProcessorExceptionType {
	MAPPING_NOT_FOUND, 
	MAPPING_NOT_MATCH,
	OTHER, 
	ILLEGAL_ARGUMENTS, 
	ILLEGAL_ACCESS, 
	INVOCATION_TARGET_EXCEPTION,
	NOT_FOUND,
	
	SERIALIZE_INIT_ERROR, SERIALIZE_ERROR, DESERIALIZE_ERROR,
	
	RUNTIME,
	
	UNSUPPORTED_ATTRIBUTE_TYPE,
	
	UNAUTHORIZED,
	
	PATH_VARIABLE_URL_DECODE, PATH_VARIABLE_FORMAT,
	
	ATTACHMENT_HANDLING_ERROR;
}
