package com.dvwsolutions.urlmapping;

public enum MappingProcessorExceptionType {
	MAPPING_NOT_FOUND, OTHER, ILLEGAL_ARGUMENTS, ILLEGAL_ACCESS, INVOCATION_TARGET_EXCEPTION,
	
	SERIALIZE_INIT_ERROR, SERIALIZE_ERROR, DESERIALIZE_ERROR,
	
	RUNTIME;
}
